package rules.Проверки;
dialect  "mvel"

import com.agorbunov.spring.drools.api.model.CreditProgram;
import com.agorbunov.spring.drools.api.model.CreditRequest;
import com.agorbunov.spring.drools.api.logger.RuleLogger;

rule "Сумма кредита"
no-loop

    when
    //    $creditProgram : CreditProgram() and
        $creditRequest : CreditRequest(askTotalCreditQty >= 10)
    //    Reester($creditRequest != null, $creditProgram != null)
        //$reester : Reester($creditRequest.askTotalCreditQty >= 10)

    then
        RuleLogger.error("###");
       // RuleLogger.error("Сумма превышает максимально допустимую по данной программе = " + $creditProgram.getMaxAmount());
       // RuleLogger.info(drools, "Сумма превышает максимально допустимую по данной программе = " + $creditProgram.getMaxAmount());
end
